---
- name: Deploy web app
  hosts: n2
  become: yes

  tasks:
  - name: Install Git
    yum:
      name: git
      state: present

  - name: Host code
    git:
      repo: https://github.com/Anu-Opp/food3.git
      dest: /var/www/html
      version: master
      force: yes
      update: yes
      accept_hostkey: yes

