---
- name: update n1 servers
  hosts: n1
  tasks:
    - name: Create directory
      file:
        path: /home/centos/pickle
        state: directory

    - name: Create directory
      file:
        path: /home/centos/pickle_1
        state: directory

- name: Update n2 servers
  hosts: n2
  tasks:
    - name: Create directory
      file:
        path: /home/centos/pickle_1
        state: directory

    - name: Create directory
      file:
        path: /home/centos/pickle_2
        state: directory

- name: Update group1 servers
  hosts: g1
  tasks:
    - name: Create directory
      file:
        path: /home/centos/group_1
        state: directory

    - name: Create directory
      file:
        path: /home/centos/group_2
        state: directory
...
