---
- name: Variables demo
  hosts: g1
  become: yes
  vars:
    mygitname: App-Opp

  tasks:
    - name: Update dynamic page
      template:
        src: dynamic-page.j2
        dest: /var/www/html/dynamic-page.html
