---
- name: update static page
  copy:
    src: static-page.html
    dest: /var/www/html/static-page.html

- name: update dynamic page
  template:
    src: dynamic-page.j2
    dest: /var/www/html/dynamic-page.html
